apiVersion: apps/v1
kind: Deployment
metadata:
  name: ouu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ouu
  template:
    metadata:
      labels:
        app: ouu
    spec:
      containers:
      - image: okteto.dev/ouu:latest
        name: ouu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "360ecd01-69a4-4775-9111-11afe01f945e"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "29aac27c-d0ec-4602-b15d-42bb2c64c72c"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
